# Generated by Django 6.0.3 on 2026-08-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_longtermmemory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=255)),
                ('role', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.RenameModel(
            old_name='LongTermMemory',
            new_name='ConversationSummary',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.AlterModelOptions(
            name='conversationsummary',
            options={'ordering': ['created_at']},
        ),
    ]
